#ESTRTURA DE DADOS QUEUE/FILA

# HEAD  --- A B C  --- TAIL
# FIRST IN FIRST OUT 
# FIFO

# DIFERENÇA FILA E PILHA:
# PILHA APENAS O ULTIMO ELEMENTO
# FILA PODE ADICIONAR NO FINAL, MAS REMOVE DO COMEÇO

# COMO NÃO ___ FAZER: COMO SE FOSSE UMA LISTA NORMAL
# SE FOSSE UMA LISTA DE 1000 INDICES TERIA QUE MUDAR OS 999 DOS OUTROS AO REMOVER OS OUTROS

#DUAS OPCOES
#CRIAR SUA PRORPIA QUEUE LOW LEVEL
